---
# tasks file for bigbluebutton

- name: Update locale (ensure LANG=en_US.UTF-8)
  lineinfile: dest=/etc/default/locale regexp=^LANG line='LANG=en_US.UTF-8'
  tags:
    - set_locale

- name: Update locale (ensure LC_ALL is absent)
  lineinfile: dest=/etc/default/locale regexp=^LC_ALL state=absent
  tags:
    - set_locale

- name: add BigBlueButton apt key
  apt_key: url=http://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc state=present


- name: BigBlueButton repo is enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb {{ bbb_apt_repo_url }} bigbluebutton-xenial main'
  tags:
    - bbb_repositories
    - repositories

- name: multiverse apt repositories are enabled
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
  tags:
    - multiverse_repositories
    - repositories

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - update_apt_cache

- name: Install apt package
  apt: name={{ item }} state=present
  with_items:
    - language-pack-en
    - software-properties-common
    - haveged
  tags:
    - bbb_dependencies

- name: apt_repository required packages are present
  apt: name=python-apt state=present
  tags:
    - bbb_role_dependencies

- name: Update all packages to the latest version
  apt:
    upgrade: dist


- name: bigbluebutton is installed
  apt: name=bigbluebutton state=present
  tags:
    - install_bbb

- name: restart bbb
  command: bbb-conf --restart
  register: bbb_restarted


- name: restart bbb
  command: bbb-conf --check
  register: bbb-checked

- name: bbb-demo is installed
  apt: name=bbb-demo state=present
  tags:
    - install_bbb_demo

- name: bbb-check is installed
  apt: name=bbb-check state=present
  tags:
    - install_bbb_check